# Generated by Django 5.0.4 on 2024-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="note",
            name="unique_words_count",
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="note",
            name="words_count",
            field=models.IntegerField(editable=False),
        ),
    ]
