# Generated by Django 5.0.4 on 2024-04-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notes_app",
            "0002_alter_note_is_archived_alter_note_unique_words_count_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="notes_app.category",
            ),
        ),
    ]
