# Generated by Django 5.0.4 on 2024-05-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0003_alter_note_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
