# Generated by Django 5.0.4 on 2024-05-01 07:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0004_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
