# Generated by Django 5.0.4 on 2024-05-03 09:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0005_category_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["is_archived"]},
        ),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
