# Generated by Django 5.0.4 on 2024-05-03 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0006_alter_category_options_alter_note_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-is_archived"]},
        ),
    ]
