# Generated by Django 5.0.4 on 2024-05-03 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0007_alter_note_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["is_archived"]},
        ),
    ]
