# Generated by Django 5.0.4 on 2024-05-04 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes_app", "0009_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notes_app.category",
            ),
        ),
    ]
